etcd:
  image: gcr.io/google_containers/etcd:2.2.1
  container_name: etcd
  command: ['/usr/local/bin/etcd', '--bind-addr=0.0.0.0:4001', '--data-dir=/var/etcd/data', '--addr=127.0.0.1:4001']
  net: host

apiserver:
  image: justingrayston/hyperkube:v1.1.1-beta.1
  container_name: apiserver
  ports:
    - "8080"
  command: ["/hyperkube", "--api-servers=http://localhost:8080",  "--address=0.0.0.0", 
            "--etcd_servers=http://etcd:4001",
            "--cluster_name=kubernetes",
            "--v=2",
            "--enable-server",
            "--hostname-override=127.0.0.1",
            "--config=/etc/kubernetes/manifests-multi",
            "--cluster-dns=10.0.0.10",
            "--cluster-domain=cluster.local"
            ]
  volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /dev:/dev
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/:/var/lib/docker:rw
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw
  net: host
  pid: host
  privileged: true

proxy:
  image: justingrayston/hyperkube:v1.1.1-beta.1
  command: ['/hyperkube', 'proxy', '--master=http://apiserver:8080', '--v=2']
  net: host
  privileged: true

# controller:
#   image: gcr.io/google_containers/hyperkube:v1.0.7
#   command: ["/hyperkube", "controller-manager", "--address=0.0.0.0", "--master=http://apiserver:8080", "--v=2"]
#   environment:
#     - "affinity:container==*apiserver*"

# scheduler:
#   image: gcr.io/google_containers/hyperkube:v1.0.7
#   command: ["/hyperkube", "scheduler", "--address=0.0.0.0", "--master=http://apiserver:8080", "--v=2"]
#   environment:
#     - "affinity:container==*apiserver*"

# kubelet:
#   image: gcr.io/google_containers/hyperkube:v1.0.7
#   command: ['/hyperkube', 'kubelet', '--containerized' , '--api_servers=http://apiserver:8080', '--v=2', '--address=0.0.0.0', '--enable_server']
#   volumes:
#     - /:/rootfs:ro
#     - /sys:/sys:ro
#     - /dev:/dev
#     - /var/run/docker.sock:/var/run/docker.sock
#     - /var/lib/docker/:/var/lib/docker:rw
#     - /var/lib/kubelet/:/var/lib/kubelet:rw
#     - /var/run:/var/run:rw
#   privileged: true
#   # A kubelet shouldn't run alongside another kubelet - One privileged kubelet per node
#   environment:
#     - "affinity:container!=*kubelet*"

# proxy:
#   image: gcr.io/google_containers/hyperkube:v1.0.7
#   command: ['/hyperkube', 'proxy', '--master=http://apiserver:8080', '--v=2']
#   privileged: true
#   # A proxy should run alongside another kubelet
#   environment:
#     - "affinity:container==*kubelet*"